### ISSUE TITLE
[auth] Users occasionally get trapped in spectator mode

### ISSUE THREAD

**Issue by MKRhere** [telecraft/telecraft#1]
After joining and leaving without auth, occasionally user gets locked into spectator mode after auth.

**Comment by MKRhere** [comment]
Investigating the database found this:

![image](https://user-images.githubusercontent.com/19621208/104856463-d7e3c000-5938-11eb-9f93-e6863014aab0.png)

Which is clearly a bug. Store somehow gets spectator while logging out without auth.

**Comment by MKRhere** [comment]
Fixed in 35f018dfb51b146c7874cd24c2464ba87955678a by avoiding a race between `data get entity` (data) and `gamemode spectator` (lock). Must reopen if issue resurfaces.

**Comment by uditkarode** [comment]
I think 81bb4da6e49b44d29e71a22e3cae51513fc74fa8 fixed this, should be fine to close it

**Comment by MKRhere** [comment]
🥳
